[workspace]
resolver = "2"
members = ["deploy", "shared"]

[workspace.dependencies]
ensko_aws = { path = "../ensko_aws" }
ensko = { path = "../ensko/ensko" }
serde_json = "1.0.68"
serde = { version = "1.0.140", features = ["derive"] }
aws-config = "1.6.2"
aws-sdk-dynamodb = "1.74.0"
