[package]
name = "logic"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
shared = { path = "../shared" }
tokio = { workspace = true }
fastrand = { workspace = true }
